version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: hiberly
      POSTGRES_DB: hiberly_gateway
  web:
    build: .
    command: gunicorn hiberly_gateway.wsgi --bind 0.0.0.0:5000 --log-file -
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
      IS_DOCKER: "true"
      DEBUG: 1
      GITLAB_KEY: "your key"
      GITLAB_SECRET: "your secret"
      GITLAB_URL: "https://gitlab.com"
    depends_on:
      - db
